using System;
namespace OpenProject.Shared
{
    // This file is automatically generated
    [System.CodeDom.Compiler.GeneratedCode("GitVersionBuild", "")]
    public static class VersionsService
    {
        public static string Version => "2.2.5-38788-load-viewp0002";
        public static string CommitInfo => "Branch.feature-38788-load-viewpoints-with-hidden-elements.Sha.83f85e3da537b65795795947105374dc7b1b8af2";
        public static string CommitDate => "2021-09-03";
        public static string CommitHash => "83f85e3da537b65795795947105374dc7b1b8af2";
        public static string InformationalVersion => "2.2.5-38788-load-viewpoints-with-hidden-elements.2+Branch.feature-38788-load-viewpoints-with-hidden-elements.Sha.83f85e3da537b65795795947105374dc7b1b8af2";
        public static DateTime BuildDateUtc { get; } = new DateTime(2021, 9, 7, 12, 13, 43, DateTimeKind.Utc);
    }
}