using System;
namespace OpenProject.Shared
{
    // This file is automatically generated
    [System.CodeDom.Compiler.GeneratedCode("GitVersionBuild", "")]
    public static class VersionsService
    {
        public static string Version => "2.2.5-chore-remove-unu0001";
        public static string CommitInfo => "12.Branch.chore-remove-unused-code.Sha.431a71a0c2711be19095b4089c084a19fd932b21";
        public static string CommitDate => "2021-07-22";
        public static string CommitHash => "431a71a0c2711be19095b4089c084a19fd932b21";
        public static string InformationalVersion => "2.2.5-chore-remove-unused-code.1+12.Branch.chore-remove-unused-code.Sha.431a71a0c2711be19095b4089c084a19fd932b21";
        public static DateTime BuildDateUtc { get; } = new DateTime(2021, 7, 23, 15, 2, 49, DateTimeKind.Utc);
    }
}